version: "3.8"

services:
  # TODO: frontend側のDockerfileを用意する
  # frontend:
  #   container_name: frontend
  #   hostname: frontend
  # depends_on:
  #   - api

  api:
    container_name: api
    hostname: api
    build:
      context: ./api
      dockerfile: ./Dockerfile
    volumes:
      - ./api/template:/template
      - ./api/output:/output
    command: sh ./type_set.sh
