version: "3.8"

services:
  frontend:
    container_name: frontend
    hostname: frontend
    image: node:20.11.1-alpine3.18
    volumes: 
      - ./frontend:/frontend
    ports:
      - 5173:5173
    command: sh -c "cd frontend/app && yarn install && yarn dev -- --host"
    depends_on:
      - api
    tty: true

  api:
    container_name: api
    hostname: api
    build:
      context: .
      dockerfile: ./docker/Dockerfile.app
    volumes:
      - ./api:/workdir
      - ./api/template:/template
      - ./api/output:/output
    ports:
      - 8000:8000
    command: uvicorn app.main:app --reload --host=0.0.0.0 --port=8000
